site_name: lsqaured
site_description: Image JSON API for content
repo_url: https://github.com/kavinjey/lsquared_interview
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/kavinjey">kavinjey</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
